gitseal

diff --git a/docker/builds/py0/bashrc b/docker/builds/py0/bashrc
--- a/docker/builds/py0/bashrc
+++ b/docker/builds/py0/bashrc
@@ -1,6 +1,9 @@
 # Just a personal .bashrc that maybe renamed and then included in the real ~/.bashrc
 # in ~/.bashrc: [[ -f ~/.bashrc.includeme ]] && source ~/.bashrc.includeme
 
+# you are in the box sending things out the jack (via /dev/fd/1 or /dev/fd/2) to the speaker (terminal) which appears on the terminals output
+# Things piped out /dev/fd/1 may be connected to the output of you terminal
+
 # XDG base directories.
 export XDG_CACHE_HOME="$HOME/.cache"
 export XDG_CONFIG_HOME="$HOME/.config"
@@ -30,10 +33,10 @@ fi
 # Set the editor and editor alias
 ######################################
 command_exists() {
-  command -v "$1" 1>&2 >/dev/null
+  command -v "$1" >/dev/null 2>&1
 }
 
-if command_exists nvim 1>&2 >/dev/null; then
+if command_exists nvim; then
   export EDITOR=nvim
   alias v='nvim'
 elif command_exists vim; then
@@ -58,15 +61,19 @@ bind -m vi-command ".":yank-last-arg # or insert-last-argument
 bind '"jj":vi-movement-mode'
 
 export IGNOREEOF=4
-# export PS1="\[$(tput setaf 7)\][\!]\[$(tput setaf 47)\][\H]\[$(tput setaf 3)\][\u]\[$(tput setaf 8)\][\D{%F %T}]\[$(tput setaf 2)\][\w]\n\[$(tput setaf 7)\][\$?][\v]\$ \[$(tput sgr0)\]"
-# the git broke sudo bash export PS1="\[$(tput setaf 7)\][\!]\[$(tput setaf 47)\][\H]\[$(tput setaf 3)\][\u]\[$(tput setaf 8)\][\D{%F %T}]\[$(tput setaf 2)\][\w]\n\[$(tput setaf 7)\][\$?][\[$(tput setaf 9)\]\$(parse_git_branch)\[$(tput setaf 7)\]][\v]\$ \[$(tput sgr0)\]"
-PS1="\[$(tput setaf 7)\][\!]\[$(tput setaf 47)\][\H]\[$(tput setaf 3)\][\u]\[$(tput setaf 8)\][\D{%F %T}]\[$(tput setaf 2)\][\w]\n\[$(tput setaf 7)\][\$?]\[$(tput setaf 7)\][\v]\$ \[$(tput sgr0)\]"
-# Make info friendly
 
+# PS1="\[$(tput setaf 7)\][\!]\[$(tput setaf 47)\][\H]\[$(tput setaf 3)\][\u]\[$(tput setaf 8)\][\D{%F %T}]\[$(tput setaf 2)\][\w]\n\[$(tput setaf 7)\][\$?]\[$(tput setaf 7)\][\v]\$ \[$(tput sgr0)\]"
+PS1='\[\e[37m\][\!]\[\e[38;5;47m\][\H]\[\e[33m\][\u]\[\e[90m\][\D{%F %T}]\[\e[32m\][\w]\n\[\e[37m\][\$?]\[\e[37m\][\v]\$ \[\e[0m\]'
+# PS1='[\!][\H][\u][\D{%F %T}][\w]\n[\$?][\v]\$ '  # no color
 checkip() {
-  exec 3<>/dev/tcp/checkip.amazonaws.com/80
-  printf "GET / HTTP/1.1\r\nHost: checkip.amazonaws.com\r\nConnection: close\r\n\r\n" >&3
-  tail -n1 <&3
+  local fd
+  exec {fd}<>/dev/tcp/checkip.amazonaws.com/80 || {
+    echo >&2 "checkip: connect failed"
+    return 1
+  }
+  printf "GET / HTTP/1.1\r\nHost: checkip.amazonaws.com\r\nConnection: close\r\n\r\n" >&"${fd}"
+  tail -n1 <&"${fd}"
+  exec {fd}>&-
 }
 
 PROMPT_DIRTRIM=10
@@ -83,17 +90,18 @@ shopt -s dirspell 2>/dev/null
 shopt -s cdspell 2>/dev/null
 shopt -s cdable_vars
 shopt -s lithist
-export HISTSIZE=50000
-export HISTFILESIZE=10000
-export HISTCONTROL="ignorespace:erasedups"
-export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
-export HISTTIMEFORMAT='%F %T '
+HISTSIZE=50000
+HISTFILESIZE=50000
+HISTCONTROL="ignorespace:ignoredups"
+HISTIGNORE="[ ]*:exit:ls:bg:fg:history:clear"
+HISTTIMEFORMAT='%F %T '
 
-CDPATH=".:~:"
+CDPATH=".:~"
 
 alias nsps='ps -eo pid,ppid,pgid,sess,stat,tty,pidns,utsns,ipcns,mntns,netns,cmd'
 alias pps='ps -eo pid,ppid,pgid,sess,stat,tty,tpgid,uname,%cpu,%mem,cmd'
 alias nps='ps -N --ppid 2 -o pid,ppid,pgid,sess,stat,tty,tpgid,uname,%cpu,%mem,cmd'
+alias psf='ps -N --ppid 2 -lwf'
 
 # Existing
 alias chown='chown --preserve-root'
@@ -103,10 +111,10 @@ alias bc='bc -l'
 alias dmesg='dmesg --color=always'
 alias chmod='chmod --preserve-root'
 alias chgrp='chgrp --preserve-root'
+alias rm='rm -v -I --preserve-root'
 alias cp='cp -i -v'
 alias grep='grep -i --color=auto'
 alias mv='mv -i -v'
-alias rm='rm -v -I --preserve-root'
 alias df='df -H'
 alias du='du -ch'
 alias ls='ls -F -h --color=always --time-style=long-iso'
@@ -119,7 +127,7 @@ alias ltr='ls -AFltrh --color=auto'
 alias lt='ls -AFlth --color=auto'
 alias g='grep'
 alias pg="pcre2grep -i"
-alias path='echo -e ${PATH//:/\\n}'
+alias path='printf "%s\n" "${PATH//:/$'"'"'\n'"'"'}"'
 alias now='date +"%T"'
 alias j='jobs -l'
 # Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0
@@ -149,22 +157,26 @@ alias jbw='journalctl -p "emerg..warning" -b'
 alias jbn='journalctl -p "emerg..notice" -b'
 alias jlb='journalctl --list-boots'
 # A load average of multi cpu system
-alias loada='cat /proc/loadavg | cut -c 1-4 | echo "scale=2; ($(</dev/stdin)/`nproc`)*100" | bc -l'
 alias cpuinfo='lscpu'
 alias xlsblk='lsblk -o name,mountpoint,fstype,size,fsused,pttype,model,vendor,serial,uuid,partuuid'
 
-home_bashrc_directory=~/.bashrc_zen.d
-
-if [[ -d "${home_bashrc_directory}" ]]; then
-  echo "Running scripts in ${home_bashrc_directory}"
-  for profile in "${home_bashrc_directory}/"*.sh; do
-    if [[ -r "$profile" ]]; then
-      echo "Sourcing: $profile"
-      . "$profile"
-    else
-      echo "Cannot read $profile, skipping..."
-    fi
-  done
-else
-  echo "Directory ${home_bashrc_directory} does not exist."
+if [[ -f ~/gitdir/skel/bash/bashrc_zen.d/zen_loader.sh ]]; then
+  source ~/gitdir/skel/bash/bashrc_zen.d/zen_loader.sh
+  zen_load
 fi
+
+# home_bashrc_directory=~/.bashrc_zen.d
+#
+# if [[ -d "${home_bashrc_directory}" ]]; then
+#   echo "Running scripts in ${home_bashrc_directory}"
+#   for profile in "${home_bashrc_directory}/"*.sh; do
+#     if [[ -r "$profile" ]]; then
+#       echo "Sourcing: $profile"
+#       . "$profile"
+#     else
+#       echo "Cannot read $profile, skipping..."
+#     fi
+#   done
+# else
+#   echo "Directory ${home_bashrc_directory} does not exist."
+# fi
